#!/usr/bin/env python3
"""
build_dashboard_v2.py — Regenerate dashboard_v2.html with latest data
─────────────────────────────────────────────────────────────────────
Reads the template, embeds latest data files, and outputs the final HTML.
Run this after verdict_engine and signal_scraper complete.
"""

import json
import csv
from pathlib import Path

# Paths
TEMPLATE_PATH = Path("dashboard/v2/dashboard_v2.html")
OUTPUT_PATH = Path("dashboard/v2/dashboard_v2.html")
DATA_CSV = Path("data/jobs_enriched_v2.csv")
DATA_SIGNALS_JSON = Path("data/signals.json")
DATA_VERDICTS_JSON = Path("data/intelligence_verdicts.json")
DATA_COMP_SIGNALS_JSON = Path("data/competitive_signals.json")


def load_csv(path):
    """Load CSV as list of dicts."""
    if not path.exists():
        print(f"⚠ {path} not found")
        return []
    try:
        with open(path) as f:
            return list(csv.DictReader(f))
    except Exception as e:
        print(f"✗ Failed to load {path}: {e}")
        return []


def load_json(path):
    """Load JSON file."""
    if not path.exists():
        print(f"⚠ {path} not found")
        return []
    try:
        with open(path) as f:
            return json.load(f)
    except Exception as e:
        print(f"✗ Failed to load {path}: {e}")
        return []


def build_dashboard():
    """Build the dashboard HTML with embedded data."""
    print("=" * 78)
    print("Building dashboard_v2.html with latest data...")
    print("=" * 78)

    # Load all data
    jobs = load_csv(DATA_CSV)
    signals = load_json(DATA_SIGNALS_JSON)
    verdicts = load_json(DATA_VERDICTS_JSON)
    comp_signals = load_json(DATA_COMP_SIGNALS_JSON)

    print(f"✓ Loaded {len(jobs)} jobs")
    print(f"✓ Loaded {len(signals)} hiring signals")
    print(f"✓ Loaded {len(verdicts)} verdicts")
    print(f"✓ Loaded {len(comp_signals)} competitive signals")

    # Read template
    if not TEMPLATE_PATH.exists():
        print(f"✗ Template not found: {TEMPLATE_PATH}")
        return False

    with open(TEMPLATE_PATH, "r") as f:
        html = f.read()

    # Inject data as window globals (before </head>)
    data_script = f"""
<script>
// ═══════════════════════════════════════════════════════════════════════
// EMBEDDED DATA — Generated by build_dashboard_v2.py
// ═══════════════════════════════════════════════════════════════════════
window.__EMBEDDED_DATA__ = {{
  jobs: {json.dumps(jobs)},
  signals: {json.dumps(signals)},
  verdicts: {json.dumps(verdicts)},
  comp_signals: {json.dumps(comp_signals)}
}};

// Intercept fetch() calls to use embedded data as fallback
const originalFetch = window.fetch;
window.fetch = function(url, opts) {{
  if (typeof url === 'string') {{
    if (url.includes('jobs_enriched_v2.csv') && window.__EMBEDDED_DATA__.jobs) {{
      return Promise.resolve({{
        ok: true,
        text: async () => {{
          const jobs = window.__EMBEDDED_DATA__.jobs;
          const headers = Object.keys(jobs[0] || {{}});
          let csv = headers.join(',') + '\\n';
          for (const row of jobs) {{
            csv += headers.map(h => {{
              const val = row[h] || '';
              return val.includes(',') ? `"${{val}}"` : val;
            }}).join(',') + '\\n';
          }}
          return csv;
        }}
      }});
    }}
    if (url.includes('signals.json') && window.__EMBEDDED_DATA__.signals) {{
      return Promise.resolve({{
        ok: true,
        json: async () => window.__EMBEDDED_DATA__.signals
      }});
    }}
  }}
  return originalFetch(url, opts);
}};
</script>
"""

    # Insert before the closing </head> tag
    if "</head>" in html:
        html = html.replace("</head>", data_script + "</head>", 1)
    else:
        print("⚠ No </head> tag found, inserting at top")
        html = data_script + html

    # Write output
    try:
        with open(OUTPUT_PATH, "w") as f:
            f.write(html)
        print(f"\n✓ Generated {OUTPUT_PATH}")
        print(f"  File size: {len(html) / 1024:.1f} KB")
        return True
    except Exception as e:
        print(f"✗ Failed to write {OUTPUT_PATH}: {e}")
        return False


if __name__ == "__main__":
    success = build_dashboard()
    exit(0 if success else 1)
